# Generated by Django 3.0.8 on 2020-08-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_MEDICINE_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=50)),
                ('medicine', models.CharField(max_length=100)),
                ('effect', models.TextField()),
                ('usage', models.TextField()),
                ('precautions', models.TextField()),
                ('reference', models.URLField()),
            ],
        ),
    ]
